build:
  version: "3.0"

cards:
  message: "Welcome to ViratBank cards related local APIs "
  contactDetails:
    name: "Shreyas - Developer"
    email: "Shreyas@viratbank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932